[package]
name = "tetor"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.27.0"
crossterm = "0.26"
toml_edit = "0.22.6"
tokio = { version = "1.43.0", features = ["full"] }
syntect = "5.0"
path-absolutize = "3.1.1"